# Generated by Django 5.0.2 on 2024-02-11 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaizntree', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='SKU',
            new_name='sku',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='in_stock',
            new_name='stock_status',
        ),
    ]
